name: Build

on: [push, workflow_dispatch]

jobs:
  Build:
    name: Mac OS X
    runs-on: macos-latest 

    steps:
    - name: Configure
      run: |
        cmake -B build -C cmake_checks_cache.txt \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_OSX_ARCHITECTURES="arm64"
        
    - name: Build
      run: |
        cmake --build build/ --config Release --parallel 3
        
    - name: Upload
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/libSDL2-2.0.0.dylib
                
