name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    name: Mac OS X
    runs-on: macos-latest 

    defaults:
      run:
        shell: sh

    strategy:
      fail-fast: false         

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: |
        cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_MODULE_PATH=/Users/runner/work/SDL/SDL/CMakeChecksCache \
        -DCMAKE_OSX_ARCHITECTURES="arm64"
        
    - name: Build
      run: |
        cmake --build build/ --config Release --parallel

    - name: Upload
      uses: actions/upload-artifact@v4.3.3
      with:
        path: /Users/runner/work/SDL/SDL/CMakeChecksCache
        
    - name: Upload2
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/libSDL2-2.0.0.dylib
                
