name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    name: Mac OS X
    runs-on: macos-latest 

    defaults:
      run:
        shell: sh

    strategy:
      fail-fast: false         

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: |
        cmake -B build -C cmake_checks_cache.txt \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_OSX_ARCHITECTURES="arm64"
        
    - name: Build
      run: |
        cmake --build build/ -t all/fast --config Release --parallel
        
    - name: Upload
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/libSDL2-2.0.0.dylib
                
