name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    name: Mac OS X
    runs-on: macos-latest 

    defaults:
      run:
        shell: sh

    strategy:
      fail-fast: false         

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        xcodebuild -project /Users/runner/work/SDL/SDL/Xcode/SDL/SDL.xcodeproj -target SDL2.dmg -configuration Release
    - name: Upload
      uses: actions/upload-artifact@v4.3.3
      with:
        path: dist/SDL2.dmg
                
